name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-sub-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Notify Start on Telegram
        run: |
          TIMESTAMP=$(TZ=Asia/Manila date +"%Y-%m-%d %H:%M:%S %Z %z")
          MESSAGE="🛠️ Build STARTED%0A"
          MESSAGE+="📦 Repository: ${{ github.repository }}%0A"
          MESSAGE+="🌱 Branch: ${{ github.ref }}%0A"
          MESSAGE+="🕒 Triggered at: ${TIMESTAMP}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=${MESSAGE}"

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Create Buildx Builder
        run: docker buildx create --use --name multiarch-builder

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Multi-Arch Image
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --builder multiarch-builder \
          --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
          -t ghcr.io/${{ github.actor }}/docker-earnapp:latest --push .

      - name: Notify Success on Telegram
        if: success()
        run: |
          TIMESTAMP=$(TZ=Asia/Manila date +"%Y-%m-%d %H:%M:%S %Z %z")
          MESSAGE="✅ Build DONE%0A"
          MESSAGE+="📦 Repository: ${{ github.repository }}%0A"
          MESSAGE+="🌱 Branch: ${{ github.ref }}%0A"
          MESSAGE+="🕒 Completed at: ${TIMESTAMP}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=${MESSAGE}"

      - name: Notify Failure on Telegram
        if: failure()
        run: |
          TIMESTAMP=$(TZ=Asia/Manila date +"%Y-%m-%d %H:%M:%S %Z %z")
          MESSAGE="❌ Build ERROR%0A"
          MESSAGE+="📦 Repository: ${{ github.repository }}%0A"
          MESSAGE+="🌱 Branch: ${{ github.ref }}%0A"
          MESSAGE+="🕒 Failed at: ${TIMESTAMP}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=${MESSAGE}"
